### ISSUE TITLE
Add of Disqus to the Nest theme for Pelican

### ISSUE THREAD

**Issue by mohcinemadkour** [molivier/nest#16]
Hi everyone 

I have an issue adding the disqus comment to my blog made bt the pelican theme nest, I have created a disqus application and I have obtained the DISQUS_SITENAME , DISQUS_PUBLIC_KEY and the DISQUS_SECRET_KEY. I added these information in the pelicanconf.py but I can not see the comment block in the end of my articles.  I have used the nest them from Github. Any idea why? thanks.

**Comment by molivier** [comment]
Hi Mochine,

To enable Disqus comment system you must set `DISQUS_SITENAME` and `SITEURL` in  publishconf.py and/or pelicanconfig.py ([Reference](https://github.com/molivier/nest/blob/master/templates/disqus_script.html#L1)).

For example in my pelicanconf.py:

```
AUTHOR = u'Matthieu OLIVIER'
SITENAME = u'molivier'
SITEURL = 'http://127.0.0.1:8000'
```
For example in my publishconf.py:

```
SITEURL = 'https://www.molivier.com'
DISQUS_SITENAME = 'molivier'
```
This only activate Disqus when publishing.

**Comment by molivier** [comment]
Mochine,

I updated README to clarify Disqus activation.
Thank you for filling this issue.
