### ISSUE TITLE
Conflicting License Declaration?

### ISSUE THREAD

**Issue by shaform** [molivier/nest#19]
Which license does this repository use?
* GPL v2 ?
https://github.com/molivier/nest/blob/0fed2cf6c09e793cc933fa59bfe44ca9a8a7b8b1/LICENSE#L1-L2
* Apache v2 ? https://github.com/molivier/nest/blob/0fed2cf6c09e793cc933fa59bfe44ca9a8a7b8b1/static/css/nest.css#L4

**Comment by molivier** [comment]
Thank you for identifying this typo. I just fix this in master branch.
